{{- if .Values.acl.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lakefs-acl.fullname" . }}-secrets
  labels:
    {{- include "lakefs-acl.labels" . | nindent 4 }}
type: Opaque
data:
  ACL_API_TOKEN: {{ .Values.acl.apiToken | b64enc | quote }}
  ACL_ENCRYPTION_KEY: {{ .Values.acl.encryptionKey | b64enc | quote }}
{{- end }}
